name: 'TeleportAssist'
version: '0.2.0-SNAPSHOT'
main: 'org.winlogon.teleportassist.TeleportAssist'
api-version: 1.21
description: 'Paper plugin providing async teleport requests with Folia compatibility'
folia-supported: true
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    ScalaLoader:
      load: BEFORE
      required: true
      join-classpath: true
