name: TpaPlugin
version: '0.1.0-SNAPSHOT'
main: 'org.winlogon.TpaPlugin'
api-version: 1.21
description: 'Normal, reasonable and simple /tpa plugin.'
folia-supported: true
commands:
  tpa:
    usage: /<command> <player>
    description: "Teleport to a player"
  tpaccept:
    usage: /<command> <player>
    description: "Accept the teleport request"
  tpahere:
    usage: /<command> <player>
    description: "Teleport a player to you"
  tpdeny:
    usage: /<command>
    description: "Deny the teleport request"
  tpcancel:
    usage: /<command>
    description: "Cancel requests sent to any player"
  back:
    usage: /<command>
    description: "Teleport you back to the last place you were"
